ALTER TABLE goc.goc_reuniones
  ADD COLUMN url_acta VARCHAR(1000),
  ADD COLUMN url_acta_alt VARCHAR(1000);

ALTER TABLE goc.goc_reuniones_puntos_orden_dia
  ADD COLUMN url_acta VARCHAR(1000),
  ADD COLUMN url_acta_alt VARCHAR(1000);

ALTER TABLE goc.goc_organos_reuniones_miembros
  ADD COLUMN url_asistencia VARCHAR(1000),
  ADD COLUMN url_asistencia_alt VARCHAR(1000);

ALTER TABLE goc.goc_reuniones_invitados
  ADD COLUMN url_asistencia VARCHAR(1000),
  ADD COLUMN url_asistencia_alt VARCHAR(1000);

CREATE TABLE goc.GOC_ORGANOS_REUNIONES_INVITS
(
  ID                 DOUBLE PRECISION,
  ORGANO_REUNION_ID  DOUBLE PRECISION NOT NULL,
  ORGANO_EXTERNO     BOOLEAN DEFAULT FALSE NOT NULL,
  REUNION_ID         DOUBLE PRECISION NOT NULL,
  ORGANO_ID          VARCHAR(400)     NOT NULL,
  NOMBRE             VARCHAR(500)     NOT NULL,
  EMAIL              VARCHAR(200)     NOT NULL,
  PERSONA_ID         DOUBLE PRECISION NOT NULL,
  URL_ASISTENCIA     VARCHAR(1000),
  URL_ASISTENCIA_ALT VARCHAR(1000)
);

ALTER TABLE goc.GOC_ORGANOS_REUNIONES_INVITS
  ADD
  CONSTRAINT GOC_ORGANOS_REUNIONES_INVI_R01
  FOREIGN KEY (ORGANO_REUNION_ID)
  REFERENCES GOC_ORGANOS_REUNIONES (ID);

ALTER TABLE goc.goc_reuniones
  ADD COLUMN aviso_primera_reunion_user VARCHAR(100),
  ADD COLUMN aviso_primera_reunion_fecha DATE;

ALTER TABLE goc.GOC_REUNIONES_PUNTOS_ORDEN_DIA
  ALTER COLUMN DESCRIPCION DROP NOT NULL;

ALTER TABLE goc.goc_organos_invitados
  ADD COLUMN solo_consulta BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE goc.goc_organos_reuniones_invits
  ADD COLUMN solo_consulta BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE goc.goc_organos_autorizados ADD COLUMN persona_email VARCHAR(1000);