alter table GOC_ORGANOS_REUNIONES_MIEMBROS ADD SUPLENTE_EMAIL VARCHAR2(200);

ALTER TABLE GOC_CONVOCANTES RENAME TO GOC_ORGANOS_AUTORIZADOS;

ALTER TABLE GOC_REUNIONES ADD NOTIFICADA NUMBER DEFAULT 0;
ALTER TABLE GOC_REUNIONES ADD CREADOR_NOMBRE VARCHAR2(2000);
ALTER TABLE GOC_REUNIONES ADD CREADOR_EMAIL VARCHAR2(200);


ALTER TABLE GOC_ORGANOS ADD INACTIVO NUMBER DEFAULT 0;

ALTER TABLE GOC_ORGANOS_REUNIONES ADD ORGANO_NOMBRE VARCHAR2(100);
ALTER TABLE GOC_ORGANOS_REUNIONES ADD TIPO_ORGANO_ID NUMBER;

ALTER TABLE GOC_ORGANOS_REUNIONES ADD EXTERNO NUMBER;
ALTER TABLE GOC_ORGANOS_REUNIONES DROP COLUMN ORGANO_EXTERNO_ID;
ALTER TABLE GOC_ORGANOS_REUNIONES DROP COLUMN ORGANO_ID;
ALTER TABLE GOC_ORGANOS_REUNIONES ADD ORGANO_ID VARCHAR2(100) NOT NULL;

ALTER TABLE GOC_REUNIONES ADD ADMITE_SUPLENCIA NUMBER DEFAULT 0;
