alter table GOC_REUNIONES ADD TELEMATICA NUMBER DEFAULT 0;
alter table GOC_REUNIONES ADD TELEMATICA_DESCRIPCION CLOB;
alter table GOC_ORGANOS_REUNIONES_MIEMBROS ADD SUPLENTE_EMAIL VARCHAR2(200);

RENAME TABLE GOC_CONVOCANTES GOC_ORGANOS_AUTORIZADOS;

ALTER TABLE GOC_REUNIONES ADD NOTIFICADA NUMBER DEFAULT 0;
ALTER TABLE GOC_REUNIONES ADD CREADOR_NOMBRE VARCHAR2(2000);
ALTER TABLE GOC_REUNIONES ADD CREADOR_EMAIL VARCHAR2(200);


ALTER TABLE GOC_ORGANOS ADD INACTIVO NUMBER DEFAULT 0;