CREATE TABLE GOC_TIPOS_ORGANO
  (
     id NUMBER  NOT NULL ,
     codigo VARCHAR2 (10) NOT NULL,
     nombre VARCHAR2 (100)  NOT NULL
  )
;

ALTER TABLE GOC_TIPOS_ORGANO ADD CONSTRAINT TIPOS_ORGANO_PK PRIMARY KEY ( id )
;

CREATE TABLE GOC_ORGANOS
  (
     id NUMBER  NOT NULL ,
     nombre VARCHAR2 (100)  NOT NULL ,
     tipo_organo_id NUMBER  NOT NULL,
     CREADOR_ID NUMBER NOT NULL,
     FECHA_CREACION DATE NOT NULL
  )
;

ALTER TABLE GOC_ORGANOS ADD CONSTRAINT ORGANOS_PK PRIMARY KEY ( id )
;

ALTER TABLE GOC_ORGANOS
      ADD CONSTRAINT GOC_ORG_TIPOS_FK FOREIGN KEY ( tipo_organo_id )
      REFERENCES GOC_TIPOS_ORGANO ( id )
;

DROP SEQUENCE HIBERNATE_SEQUENCE
;

CREATE SEQUENCE HIBERNATE_SEQUENCE
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


GRANT SELECT ON HIBERNATE_SEQUENCE TO UJI_REUNIONES;
