CREATE TABLE UJI_REUNIONES.GOC_P_ORDEN_DIA_ACUERDOS
(
  ID               NUMBER                       NOT NULL,
  PUNTO_ID         NUMBER                       NOT NULL,
  DESCRIPCION      VARCHAR2(2048 BYTE)          NOT NULL,
  MIME_TYPE        VARCHAR2(512 BYTE)           NOT NULL,
  NOMBRE_FICHERO   VARCHAR2(512 BYTE)           NOT NULL,
  FECHA_ADICION    DATE                         DEFAULT SYSDATE               NOT NULL,
  DATOS            BLOB                         NOT NULL,
  CREADOR_ID       NUMBER                       NOT NULL,
  DESCRIPCION_ALT  VARCHAR2(2048 BYTE)
);

ALTER TABLE UJI_REUNIONES.GOC_P_ORDEN_DIA_ACUERDOS ADD (
  CONSTRAINT FK_ORDENDIA_ACUERDOS_REUNION
  FOREIGN KEY (PUNTO_ID)
  REFERENCES UJI_REUNIONES.GOC_REUNIONES_PUNTOS_ORDEN_DIA (ID)
  ENABLE VALIDATE);