alter table GOC_REUNIONES add URL_GRABACION VARCHAR2(4000);
alter table GOC_REUNIONES add PUBLICA NUMBER;

CREATE TABLE GOC_REUNIONES_COMENTARIOS
(
  ID          NUMBER PRIMARY KEY,
  COMENTARIO  CLOB NOT NULL,
  REUNION_ID  NUMBER NOT NULL,
  CREADOR_ID  NUMBER NOT NULL,
  CREADOR_NOMBRE VARCHAR2(1000),
  FECHA       DATE   NOT NULL DEFAULT SYSDATE
);

alter table GOC_REUNIONES_COMENTARIOS
  add constraint fk_comentarios_reuniones foreign key (reunion_id) references goc_reuniones(id);

alter table GOC_REUNIONES_PUNTOS_ORDEN_DIA add PUBLICO NUMBER DEFAULT 0;

CREATE TABLE GOC_CONVOCANTES
(
   id NUMBER  NOT NULL ,
   persona_id NUMBER  NOT NULL ,
   persona_nombre VARCHAR2(1000)  NOT NULL ,
   organo_id VARCHAR2(100)  NOT NULL,
   organo_externo NUMBER  NOT NULL
);

alter table GOC_ORGANOS_REUNIONES_MIEMBROS ADD SUPLENTE_ID NUMBER;
alter table GOC_ORGANOS_REUNIONES_MIEMBROS ADD SUPLENTE_NOMBRE VARCHAR2(1000);
alter table GOC_ORGANOS_REUNIONES_MIEMBROS ADD ASISTENCIA_CONFIRMADA NUMBER;
alter table GOC_REUNIONES ADD ARCHIVADA NUMBER;
alter table GOC_REUNIONES ADD MIEMBRO_RESPONSABLE_ACTA_ID NUMBER;
alter table GOC_REUNIONES ADD TELEMATICA NUMBER;
alter table GOC_REUNIONES ADD TELEMATICA_DESCRIPCION CLOB;
