alter table GOC_REUNIONES ADD TELEMATICA NUMBER DEFAULT 0 NOT NULL;
alter table GOC_REUNIONES ADD TELEMATICA_DESCRIPCION CLOB;

RENAME TABLE GOC_CONVOCANTES GOC_ORGANOS_AUTORIZADOS;

ALTER TABLE GOC_REUNIONES ADD NOTIFICADA NUMBER DEFAULT 0 NOT NULL;

create or replace view GOC_VW_ASIST_NOTIF_PENDIENTE as
  select m.*
  from GOC_ORGANOS_REUNIONES_MIEMBROS m inner join GOC_REUNIONES r on r.id = m.reunion_id
  WHERE r.completada is null or r.completada = 0
    AND r.fecha > SYSDATE AND r.fecha < SYSDATE + 1;