CREATE TABLE goc_reuniones_invitados (
  id             NUMBER         NOT NULL PRIMARY KEY,
  reunion_id     NUMBER         NOT NULL,
  persona_id     NUMBER         NOT NULL,
  persona_nombre VARCHAR2(1000) NOT NULL
);

ALTER TABLE UJI_REUNIONES.GOC_REUNIONES_INVITADOS
  ADD
  CONSTRAINT GOC_REUNIONES_INVITADOS_R01
  FOREIGN KEY (REUNION_ID)
  REFERENCES UJI_REUNIONES.GOC_REUNIONES (ID);

CREATE INDEX UJI_REUNIONES.UJI_reuniones_invitados_reu_i
  ON UJI_REUNIONES.GOC_REUNIONES_INVITADOS
  (REUNION_ID);


