alter table GOC_REUNIONES ADD TELEMATICA NUMBER DEFAULT 0 NOT NULL;
alter table GOC_REUNIONES ADD TELEMATICA_DESCRIPCION CLOB;
alter table GOC_ORGANOS_REUNIONES_MIEMBROS ADD SUPLENTE_EMAIL VARCHAR2(200);

RENAME TABLE GOC_CONVOCANTES GOC_ORGANOS_AUTORIZADOS;

ALTER TABLE GOC_REUNIONES ADD NOTIFICADA NUMBER DEFAULT 0 NOT NULL;